version: '3'

services:
  redis-master:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  redis-replica:
    image: redis:alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    restart: always

  app1:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    depends_on:
      - redis-master
    restart: always

  app2:
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env.development
    depends_on:
      - redis-master
    restart: always

  app3:
    build: .
    ports:
      - "8082:8080"
    env_file:
      - .env.development
    depends_on:
      - redis-master
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2
      - app3
    restart: always
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

volumes:
  redis-data:
  prometheus-data:
  grafana-data: